
export const centralVisayasPorts = [
  "Cebu International Port",
  "Pier 1 Cebu",
  "Pier 2 Cebu",
  "Pier 3 Cebu",
  "Pier 4 Cebu",
  "Port of Tagbilaran",
  "Port of Dumaguete",
  "Port of Toledo",
  "Port of Tubigon",
  "Port of Getafe",
  "Port of Ubay",
  "Port of Jagna",
  "Port of Loon",
  "Port of Talibon",
  "Port of Mandaue",
  "Port of Siquijor",
  "Port of Larena",
  "Port of Ormoc",
  "Port of Bacolod",
  "Port of Bogo",
  "Port of Santander",
  "Port of Danao",
  "Port of Carmen",
  "Port of Hagnaya"
];
